apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    argocd/app-selector: "app.kubernetes.io/managed-by=argocd-autopilot"
  name: argocd-autopilot
spec:
  lifecycle: production
  owner: my-team
  type: service
