
security_policy: us-only
ssl_policy: tls-12

domain: backstage2.igniteme.dev

gke_project_id: project-x-bootstrap
app_project_id: project-x-bootstrap
repo_name: backstage

appConfig:
  app:
    baseUrl: https://backstage2.igniteme.dev
    title: Backstage Maven Wave
  backend:
    baseUrl: https://backstage2.igniteme.dev
    cors:
      origin: https://backstage2.igniteme.dev
    database:
      connection:
        host: "34.1.1.1"
        user: backstage-user
        database: "prod-db"
        ssl:
          rejectUnauthorized: false
  
  
  lighthouse:
    baseUrl: https://backstage.igniteme.dev/lighthouse-api
  techdocs:
    storageUrl: https://backstage.igniteme.dev/api/techdocs/static/docs
    requestUrl: https://backstage.igniteme.dev/api/techdocs
